
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-6pm-2
pull_requests: [{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-README-table","number":49,"title":"KL- Added readme table","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/49"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-README-title","number":48,"title":"KL - added title and links to README","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/48"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Organizations-PUT","number":47,"title":"KL - Completed Organizations put","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/47"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Organizations-DELETE","number":46,"title":"KL completed organizations delete","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/46"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Organizations-GET","number":45,"title":"KL - organizations for single end point","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/45"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Organizations-Controller","number":44,"title":"KL - Completed Organizations Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/44"},{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"Kevin-Organizations","number":43,"title":"kj - created database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/43"}]
