
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-6pm-2
pull_requests: [{"author":{"id":"U_kgDOB3Dxlg","is_bot":false,"login":"DemirInce","name":""},"headRefName":"Demir-MenuItemReview-Get","number":61,"title":"Demir menu item review get and tests done","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/61"},{"author":{"id":"U_kgDOB3Dxlg","is_bot":false,"login":"DemirInce","name":""},"headRefName":"Demir-MenuItemReview-Delete","number":60,"title":"Demir menu item review delete and tests done","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/60"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItems-create-controller","number":58,"title":"Ucsb dining commons menu items create controller (get all and post)","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/58"},{"author":{"id":"U_kgDOB2-wIw","is_bot":false,"login":"thienanvuu","name":"Thienan Vu"},"headRefName":"Thienan-RecReq-Put","number":56,"title":"Completed Put Endpoint for Recommendation Request","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/56"},{"author":{"id":"U_kgDOB2-wIw","is_bot":false,"login":"thienanvuu","name":"Thienan Vu"},"headRefName":"Thienan-RecReq-Delete","number":53,"title":"Completed Delete Endpoint for RecReq","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/53"}]
