
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: team02-w24-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItems-delete-endpoint","number":67,"title":"Mb ucsb dining commons menu items delete endpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/67"},{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-UCSBDiningCommonsMenuItems-put-endpoint","number":66,"title":"Mb ucsb dining commons menu items put endpoint","url":"https://github.com/ucsb-cs156-w24/team02-w24-6pm-2/pull/66"}]
